name: Build libpcap

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  # Linux builds with autotools
  linux-autotools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        config: [default, shared, static, debug, coverage]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          pkg-config \
          flex \
          bison \
          libnl-3-dev \
          libnl-genl-3-dev \
          libssl-dev \
          libusb-1.0-0-dev \
          libbluetooth-dev \
          libdbus-1-dev \
          libcap-dev \
          libseccomp-dev
      
    - name: Setup compiler
      run: |
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          sudo apt-get install -y clang
          export CC=clang
          export CXX=clang++
        else
          export CC=gcc
          export CXX=g++
        fi
        
    - name: Bootstrap autotools
      run: |
        autoreconf -fiv
        
    - name: Configure
      run: |
        case "${{ matrix.config }}" in
          "shared")
            ./configure --enable-shared --disable-static --prefix=$GITHUB_WORKSPACE/install
            ;;
          "static")
            ./configure --disable-shared --enable-static --prefix=$GITHUB_WORKSPACE/install
            ;;
          "debug")
            ./configure --enable-debug --prefix=$GITHUB_WORKSPACE/install CFLAGS="-g -O0"
            ;;
          "coverage")
            ./configure --enable-shared --prefix=$GITHUB_WORKSPACE/install CFLAGS="--coverage -O0"
            ;;
          *)
            ./configure --prefix=$GITHUB_WORKSPACE/install
            ;;
        esac
        
    - name: Build
      run: |
        make -j$(nproc)
        
    - name: Test
      run: |
        make check  # Tests might fail in CI environment
        
    - name: Install
      run: |
        make install
        
    - name: Verify installation
      run: |
        export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/install/lib/pkgconfig:$PKG_CONFIG_PATH
        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/install/lib:$LD_LIBRARY_PATH
        pkg-config --exists libpcap
        pkg-config --modversion libpcap
        ls -la $GITHUB_WORKSPACE/install/lib/
        ls -la $GITHUB_WORKSPACE/install/include/

  # Linux builds with CMake
  linux-cmake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Release, Debug, RelWithDebInfo]
        config: [default, shared, static]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          pkg-config \
          libnl-3-dev \
          libnl-genl-3-dev \
          libssl-dev \
          libusb-1.0-0-dev \
          libbluetooth-dev \
          libdbus-1-dev \
          libcap-dev \
          libseccomp-dev
      
    - name: Setup compiler
      run: |
        if [ "${{ matrix.compiler }}" = "clang" ]; then
          sudo apt-get install -y clang
          export CC=clang
          export CXX=clang++
        else
          export CC=gcc
          export CXX=g++
        fi
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        case "${{ matrix.config }}" in
          "shared")
            cmake .. \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DBUILD_SHARED_LIBS=ON \
              -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install
            ;;
          "static")
            cmake .. \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DBUILD_SHARED_LIBS=OFF \
              -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install
            ;;
          *)
            cmake .. \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install
            ;;
        esac
        
    - name: Build
      run: |
        cd build
        make -j$(nproc)
        
    - name: Test
      run: |
        cd build
        make check
        
    - name: Install
      run: |
        cd build
        make install
        
    - name: Verify installation
      run: |
        export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/install/lib/pkgconfig:$PKG_CONFIG_PATH
        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/install/lib:$LD_LIBRARY_PATH
        pkg-config --exists libpcap
        pkg-config --modversion libpcap
        ls -la $GITHUB_WORKSPACE/install/lib/
        ls -la $GITHUB_WORKSPACE/install/include/
